In [6]:
import cv2
import numpy as np

# Load Yolo
net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")
classes = []
with open("coco.names", "r") as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getLayerNames()
output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
colors = np.random.uniform(0, 255, size=(len(classes), 3))

In [7]:


# Loading image
img = cv2.imread("yolodetection.jpg")
img = cv2.resize(img, None, fx=0.4, fy=0.2 )
height, width, channels = img.shape

# Detecting objects


In [8]:
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

32

In [9]:
blob = cv2.dnn.blobFromImage(img, 0.00392, (416, 416), (0, 0, 0), True, crop=False)

net.setInput(blob)
outs = net.forward(output_layers)

# Showing informations on the screen
class_ids = []
confidences = []
boxes = []
for out in outs:
    for detection in out:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]
        if confidence > 0.2:
            # Object detected
            center_x = int(detection[0] * width)
            center_y = int(detection[1] * height)
            w = int(detection[2] * width)
            h = int(detection[3] * height)

            # Rectangle coordinates
            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)

indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
print(indexes)
font = cv2.FONT_HERSHEY_PLAIN
for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i] 
        label = str(classes[class_ids[i]])
        color = colors[i]
        cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
        cv2.putText(img, label, (x, y + 30), font, 3, color, 3)


#cv2.imshow("Image", img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
cv2.imwrite('yolodetected.jpg',img)

[[1]
 [6]
 [9]
 [4]
 [3]
 [7]]


array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

array([[[195, 204, 207],
        [192, 205, 207],
        [191, 207, 206],
        ...,
        [157, 178, 179],
        [158, 178, 179],
        [164, 177, 179]],

       [[190, 205, 207],
        [186, 206, 207],
        [182, 206, 208],
        ...,
        [146, 179, 180],
        [152, 178, 180],
        [160, 179, 182]],

       [[188, 205, 208],
        [183, 206, 208],
        [179, 208, 209],
        ...,
        [142, 180, 182],
        [145, 177, 179],
        [154, 178, 180]],

       ...,

       [[ 12,  17,  16],
        [ 13,  18,  17],
        [ 14,  19,  18],
        ...,
        [ 95, 119, 115],
        [ 97, 118, 115],
        [103, 120, 117]],

       [[ 14,  16,  16],
        [ 14,  16,  16],
        [ 14,  19,  18],
        ...,
        [ 96, 118, 115],
        [100, 118, 115],
        [102, 116, 114]],

       [[ 13,  15,  15],
        [ 15,  17,  17],
        [ 14,  16,  16],
        ...,
        [ 96, 115, 112],
        [ 99, 114, 112],
        [103, 114, 112]]

True